#!/bin/bash

# Fix PATH for conda in non-interactive shells
export PATH="/opt/miniconda3/bin:$PATH"

TRADING_AGENTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

cd "$TRADING_AGENTS_DIR"
# Load .env file properly (handles paths with spaces)
set -a
source .env
set +a

# Configuration
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONDA_ENV="tradingagents"
CONDA_PATH="/opt/miniconda3"

# Thread ID parameter for openclaw message
THREAD_PARAM=""
if [ -n "$MESSAGE_THREAD" ]; then
    THREAD_PARAM="--thread-id $MESSAGE_THREAD"
fi

# Logging helper
log() {
    echo "[$(date '+%H:%M:%S')] $*" >&2
}

# Logging helper
log() {
    echo "[$(date '+%H:%M:%S')] $*" >&2
}

# Parse Arguments
DATE=$(date +%Y-%m-%d)
IGNORE_EXISTING="false"

while [[ $# -gt 0 ]]; do
    case $1 in
        --ticker)
            TICKER="$2"
            shift 2
            ;;
        --date)
            DATE="$2"
            shift 2
            ;;
        --ignore-existing)
            IGNORE_EXISTING="$2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

# Validate
if [ -z "$TICKER" ]; then
    log "❌ Error: Ticker is required"
    exit 1
fi

TICKER=$(echo "$TICKER" | tr '[:lower:]' '[:upper:]')

# Setup
log "🚀 Starting workflow for $TICKER"
log "📢 开始分析 $TICKER ..."

source "$CONDA_PATH/etc/profile.d/conda.sh"
conda activate $CONDA_ENV

PYTHON_BIN="$CONDA_PATH/envs/$CONDA_ENV/bin/python"

REPORT_FILE="$TRADING_AGENTS_DIR/eval_results/$TICKER/TradingAgentsStrategy_logs/full_states_log_$DATE.json"
SHOULD_RUN="true"

# 1. Check existing report
if [ "$IGNORE_EXISTING" != "true" ] && [ -f "$REPORT_FILE" ]; then
    log "✅ Found cached report, skipping AI analysis"
    SHOULD_RUN="false"
fi

# 2. Run Analysis if needed
if [ "$SHOULD_RUN" == "true" ]; then
    log "Running TradingAgents AI analysis..."
    openclaw message send -m "我已安排您的金融分析团队为您分析 $TICKER ，预计10-30分钟..." --channel telegram --target $MESSAGE_TARGET $THREAD_PARAM
    # Ensure PATH is correct for subprocess calls
    PATH="/opt/miniconda3/bin:$PATH" $PYTHON_BIN -u -m start.main --ticker $TICKER --date $DATE
fi

# Verify report exists
if [ ! -f "$REPORT_FILE" ]; then
    log "❌ Report not found: $REPORT_FILE"
    log "💥 $TICKER 分析失败：报告文件未生成"
    openclaw message send -m "❌ $TICKER 分析失败：报告文件未生成" --channel telegram --target $MESSAGE_TARGET $THREAD_PARAM
    conda deactivate
    exit 1
fi

log "✅ Report generated: $REPORT_FILE"

# 3. Translate to docbase
DOC_DIR="${DOC_DIR:-~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Finance}"
REL_REPORT_PATH="Reports/$TICKER/$DATE.md"
FULL_REPORT_PATH="$DOC_DIR/$REL_REPORT_PATH"

NEED_TRANSLATION="true"

if [ "$IGNORE_EXISTING" != "true" ] && [ -f "$FULL_REPORT_PATH" ]; then
    if grep -q "Generated by Genius ⚡" "$FULL_REPORT_PATH" 2>/dev/null; then
        log "✅ Using cached docbase report"
        NEED_TRANSLATION="false"
    fi
fi

if [ "$NEED_TRANSLATION" == "true" ]; then
    log "Translating report to Chinese..."

    openclaw message send -m "现在您的金融助理团队正在为您编写 $TICKER 的报告" --channel telegram --target $MESSAGE_TARGET $THREAD_PARAM
    
    TEMP_DIR=$(mktemp -d)
    TEMP_MD="$TEMP_DIR/report.md"

    $PYTHON_BIN "$SKILL_DIR/translate_report.py" "$TICKER" "$DATE" "$REPORT_FILE" "$TEMP_MD"

    if [ ! -f "$TEMP_MD" ] || ! grep -q "Generated by Genius ⚡" "$TEMP_MD"; then
        log "❌ Translation failed"
        openclaw message send -m "❌ $TICKER 翻译失败：中文报告未生成" --channel telegram --target $MESSAGE_TARGET $THREAD_PARAM
        
        rm -rf "$TEMP_DIR"
        conda deactivate
        exit 1
    fi

    mkdir -p "$(dirname "$FULL_REPORT_PATH")"
    cat "$TEMP_MD" > "$FULL_REPORT_PATH"
    rm -rf "$TEMP_DIR"

    log "✅ Saved to docbase: $REL_REPORT_PATH"
fi

# 4. Generate notification - 使用缓存避免重复调用 LLM
SUMMARY_FILE="/tmp/summary_${TICKER}_${DATE}.txt"

if [ "$IGNORE_EXISTING" != "true" ] && [ -f "$SUMMARY_FILE" ]; then
    log "✅ Using cached summary"
else
    log "Generating summary notification..."

    openclaw message send -m "$TICKER 完整的报告已为您保存在文档库 $REL_REPORT_PATH ，我正在阅读报告，马上为您汇报摘要" --channel telegram --target $MESSAGE_TARGET $THREAD_PARAM

    cat "$FULL_REPORT_PATH" | $PYTHON_BIN "$SKILL_DIR/summarize_notification.py" "$TICKER" "$DATE" "$SUMMARY_FILE"
    log "✅ Summary ready: $SUMMARY_FILE"
fi

# 4. 发送报告摘要给用户
if [ -f "$SUMMARY_FILE" ]; then
    log "📤 发送报告摘要给用户..."
    SUMMARY_CONTENT=$(cat "$SUMMARY_FILE")
    openclaw message send -m "$SUMMARY_CONTENT" --channel telegram --target $MESSAGE_TARGET $THREAD_PARAM
    log "✅ 通知已发送"
else
    openclaw message send -m "❌ $TICKER 摘要生成失败" --channel telegram --target $MESSAGE_TARGET $THREAD_PARAM
    log "⚠️  Summary file not found"
fi

conda deactivate
